version: '3'

services:
  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  rate-limiter:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    expose:
      - ${RATELIMIT_EXPOSE_PORT}
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    environment:
      - TZ=Asia/Tehran
    depends_on:
      - rate-limiter